#%RAML 1.0 DataType
 properties:
          EmployeeName:
            required: true
          EmployeeID:
            required: true
          EmployeeDesignation:
            required: true
            minLength: 2
            maxLength: 8